routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('blog.home');
});


Route::get('/chat', function () {
    return view('chat.index');
});

// плохая запись - не писать код в файле маршрутов
Route::post('/messages', function (Illuminate\Http\Request $request) {
  //  App\Events\Message::dispatch($request->input('body'));
   // App\Events\PrivateChat::dispatch($request->input('body'));
    App\Events\PrivateChat::dispatch($request->all());
});

/*
 * Выводим все задачи
 */
//Route::get('/tasks', function () {
//    $tasks = DB::table('tasks')->get();
//    //dd( $tasks );
//    return view('tasks.index', compact('tasks'));
//});
// То же самое через контроллер модели
//Route::get('/tasks', function () {
//    $tasks = App\Task::all(); // все его значения
//    return view('tasks.index', compact('tasks'));
//});

/// Ну а лучше через специальный контроллер
Route::get('/tasks', 'TasksController@index');


/*
 * Выводим выполненные задачи
 */
//Route::get('/incomplete-tasks', function () {
//    $tasks = App\Task::incomplete(); // все его значения
//    return view('tasks.index', compact('tasks'));
//});

/*
 * Выводим одну задачу подробно
 */
//Route::get('/tasks/{task}', function ( $id ) {
//    $task = DB::table('tasks')->find( $id );
////   dd( $task );  //- как print_r();
//    return view('tasks.show', compact('task'));
//});

//Route::get('/tasks/{task}', function ( $id ) {
//    $task = App\Task::find( $id );
//    return view('tasks.show', compact('task'));
//});

/// Ну а лучше через специальный контроллер
Route::get('/tasks/{task}', 'TasksController@show');



Route::get('/posts', 'PostsController@index');

//Route::get('/send-test-mail', 'MailController@send');


Auth::routes();
Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
});

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/category', 'CategoryController', ['as' => 'admin']);
    Route::resource('/article', 'ArticleController', ['as' => 'admin']);
    Route::group(['prefix'=>'user_managment', 'namespace'=>'UserManagment'], function() {
        Route::resource('/user', 'UserController', ['as' => 'admin.user_managment']);
    });
});


// slug? может быть, а может и не быть
Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category');
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article');

Route::get('/start/get-json', 'TestController@getJson');
Route::get('/start/data-chart', 'TestController@dataChart');
Route::get('/start/random-chart', 'TestController@chartRandom');
Route::get('/start/socket-chart', 'TestController@newEvent');
Route::get('/start/send-message', 'TestController@newMessage');
Route::get('/start/send-private-message', 'TestController@newPrivateMessage');


// комнаты
Route::get('/room/{room}', function(App\Room $room) {
    return view('chat.room',
        ['room' => $room]
    );
});

resources/views/admin/layouts/app_admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body>
<div id="app">
    <div class="container">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        Laravel
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">

                        <li>
                            <a href="{{route('admin.index')}}">Админ панель</a>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                Меню <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ route('admin.category.index') }}"> Категориии</a></li>
                                <li> <a href="{{route('admin.article.index')}}">Новости</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                Управление пользователями <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ route('admin.user_managment.user.index') }}">Пользователи</a></li>
                            </ul>
                        </li>
                    </ul>



                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else


                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-to
                                   ggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>
        @yield('content')
    </div>
</div>
{{--визуальный редактор--}}
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>

<!-- JavaScripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}" defer></script>

</body>
</html>