routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('blog.home');
});


Route::get('/chat', function () {
    return view('chat.index');
});

// плохая запись - не писать код в файле маршрутов
Route::post('/messages', function (Illuminate\Http\Request $request) {
  //  App\Events\Message::dispatch($request->input('body'));
   // App\Events\PrivateChat::dispatch($request->input('body'));
    App\Events\PrivateChat::dispatch($request->all());
});

/*
 * Выводим все задачи
 */
//Route::get('/tasks', function () {
//    $tasks = DB::table('tasks')->get();
//    //dd( $tasks );
//    return view('tasks.index', compact('tasks'));
//});
// То же самое через контроллер модели
//Route::get('/tasks', function () {
//    $tasks = App\Task::all(); // все его значения
//    return view('tasks.index', compact('tasks'));
//});

/// Ну а лучше через специальный контроллер
Route::get('/tasks', 'TasksController@index');


/*
 * Выводим выполненные задачи
 */
//Route::get('/incomplete-tasks', function () {
//    $tasks = App\Task::incomplete(); // все его значения
//    return view('tasks.index', compact('tasks'));
//});

/*
 * Выводим одну задачу подробно
 */
//Route::get('/tasks/{task}', function ( $id ) {
//    $task = DB::table('tasks')->find( $id );
////   dd( $task );  //- как print_r();
//    return view('tasks.show', compact('task'));
//});

//Route::get('/tasks/{task}', function ( $id ) {
//    $task = App\Task::find( $id );
//    return view('tasks.show', compact('task'));
//});

/// Ну а лучше через специальный контроллер
Route::get('/tasks/{task}', 'TasksController@show');



Route::get('/posts', 'PostsController@index');

//Route::get('/send-test-mail', 'MailController@send');


Auth::routes();
Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
});

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/category', 'CategoryController', ['as' => 'admin']);
    Route::resource('/article', 'ArticleController', ['as' => 'admin']);
    Route::group(['prefix'=>'user_managment', 'namespace'=>'UserManagment'], function() {
        Route::resource('/user', 'UserController', ['as' => 'admin.user_managment']);
    });
});


// slug? может быть, а может и не быть
Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category');
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article');

Route::get('/start/get-json', 'TestController@getJson');
Route::get('/start/data-chart', 'TestController@dataChart');
Route::get('/start/random-chart', 'TestController@chartRandom');
Route::get('/start/socket-chart', 'TestController@newEvent');
Route::get('/start/send-message', 'TestController@newMessage');
Route::get('/start/send-private-message', 'TestController@newPrivateMessage');


// комнаты
Route::get('/room/{room}', function(App\Room $room) {
    return view('chat.room',
        ['room' => $room]
    );
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str; // для генерации слага


class Article extends Model
{
    protected $fillable = ['title', 'slug', 'description_short', 'description', 'image', 'image_show', 'meta_title', 'published', 'viewed', 'created_by', 'modified_by'];

    // делаем слаг
    public function setSlugAttribute($value) {
        $this->attributes['slug'] = Str::slug( mb_substr($this->title, 0, 40) . "-" . \Carbon\Carbon::now()->format('dmyHi'), '-');
    }

    // Полиморфная связь с категориями
    public function categories() {
        return $this->morphToMany('App\Category', 'categoryable'); //categoryable - приставка от categoryable_id
    }

    public function scopeLastArticles($query, $count) {
        return $query->orderBy('created_by', 'desc')->take($count)->get();
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.articles.index', [
            'articles' => Article::orderBy('created_at', 'desc')->paginate(3)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.articles.create',[
            'article' => [],
            'categories' => Category::with('children')->where('parent_id', 0)->get(),
            'delimiter' => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $article = Article::create($request->all());
        if($request->input('categories')) :
            $article->categories()->attach($request->input('categories'));
        endif;
        return redirect()->route('admin.article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('admin.articles.edit', [
        'article' => $article,
        'categories' => Category::with('children')->where('parent_id', 0)->get(),
        'delimiter' => ''

        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $article->update($request->except('slug'));

        // отсоединяем категории
        $article->categories()->detach();

        if($request->input('categories')) :
            $article->categories()->attach($request->input('categories'));
        endif;

        return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        // отсоединяем категории
        $article->categories()->detach();
        $article->delete();

        return redirect()->route('admin.article.index');

    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('title') Создание Новости @endslot
            @slot('parent') Главная @endslot
            @slot('aktive') Ноости @endslot
        @endcomponent

        <hr>

        <form action="{{route('admin.article.store')}}" method="post">
            {{ csrf_field() }}
            @include('admin.articles.partials.form')

            <input type="hidden" name="created_by" value="{{Auth::id()}}">
        </form>

    </div>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('title') Редактирование Новости @endslot
            @slot('parent') Главная @endslot
            @slot('aktive') Ноости @endslot
        @endcomponent

        <hr>

        <form action="{{route('admin.article.update', $article)}}" method="post">
            {{ csrf_field() }}
            @include('admin.articles.partials.form')
            <input type="hidden" name="_method" value="put" >
            <input type="hidden" name="modified_by" value="{{Auth::id()}}">
        </form>

    </div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="content">
        @component('admin.components.breadcrumb')
            @slot('title') Список новостей @endslot
            @slot('parent') Главная @endslot
            @slot('aktive') Новости @endslot
        @endcomponent
    </div>

    <a href="{{route('admin.article.create')}}" class="btn btn-primary pull-right"> Создать новость</a>

    <table>
        @foreach ($articles as $article)
            <tr>
                <td>
                    {{$article->title}}
                </td>
                <td>
                    |  <a href="{{route('admin.article.edit', $article)}}"> Изменить</a>
                </td>

                <td>
                    <form action="{{route('admin.article.destroy', $article)}}" method="post" onsubmit="if(confirm('Удалить?')) { return true } else { return false }" >
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="delete" >
                        <button type="submit" class="btn">Удалить</button>
                    </form>
                </td>
            </tr>
        @endforeach

        <tr>
            <td colspan="2">
                <ul class="pagination pull-right">
                    {{$articles->links()}}
                </ul>

            </td>
        </tr>

    </table>

@endsection